name: Scheduled build
on:
  schedule:
    - cron: '*/2 * * * *'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'ebc-2in2crc/wareki'
          path: 'wareki'
      - name: ls
        run: ls wareki
